config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
resources :houses do
  resources :owners
end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  has_many :owners, dependent: :destroy
    validates :Address, presence: true, length: { minimum: 5 }
    has_one_attached :image
  end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:number_of_rooms, :Address, :Price)
    end
    private
def house_params
  params.require(:house).permit(:number_of_rooms, :Address, :Price, :image)
end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    def create
        @house = House.find(params[:house_id])
        @owner = @house.owners.create(owner_params)
        redirect_to house_path(@house)
      end
      def destroy
        @house = House.find(params[:house_id])
        @owner = @house.owners.find(params[:id])
        @owner.destroy
        redirect_to house_path(@house)
      end
     
      private
        def owner_params
          params.require(:owner).permit(:Name, :Email, :Phone)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number_of_rooms %>
    <%= form.number_field :number_of_rooms %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_area :Address %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price %>
  </div>

  
  <p>
  <%= form.label :image %><br>
  <%= form.file_field :image %>
</p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Number of rooms</th>
      <th>Address</th>
      <th>Price</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.number_of_rooms %></td>
        <td><%= house.Address %></td>
        <td><%= house.Price %></td>
        
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Fill Your House Information', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of rooms:</strong>
  <%= @house.number_of_rooms %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.Address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.Price %>
</p>

<h2>owners</h2>
<%= render @house.owners %>

<h2>Add a OwnerInformation:</h2>
<%= render 'owners/form' %>

<p>
<strong>Image:</strong>
<%= image_tag @house.image %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExImage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_with(model: [ @house, @house.owners.build ], local: true) do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
  <p>
    <%= form.label :Email %><br>
    <%= form.email_field :Email %>
  </p>
  <p>
  <%= form.label :Phone %><br>
  <%= form.number_field :Phone %>
</p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/owners/_owner.html.erb
<% @house.owners.each do |owner| %>
    <p>
      <strong>Name:</strong>
      <%= owner.Name %>
    </p>
   
    <p>
      <strong>Email:</strong>
      <%= owner.Email %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= owner.Phone %>
    </p>
    <p>
  <%= link_to 'Destroy owner', [owner.house, owner],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
  <% end %>

app/views/welcome/index.html.erb
<h1>Welcome to House Seller</h1>
<h3><%= link_to 'View House Information', controller: 'houses' %></h3>